### ISSUE TITLE
Readme is incorrect

### ISSUE THREAD

**Issue by viveleroi** [emerleite/node-gravatar#14]
The readme usage example is incorrect, quite a bit:

`var gravatar = require('gravatar')` should be `gravatar = require('node-gravatar')`

and

`gravatar.url(email, options, https=false);` should be `gravatar.get(email, rating, size, default)`

Also, please use an object for config so that if I want to declare a size without a rating, I don't need to pass an empty argument.

**Comment by emerleite** [comment]
Thanks viveleroi. I'll correct the docs.

About the object, I'm planning the 2.0 version with a cleanner API.

Cheers,

**Comment by emerleite** [comment]
Do not make sense anymore.
