### ISSUE TITLE
Drop the protocol from the url

### ISSUE THREAD

**Issue by ProLoser** [emerleite/node-gravatar#15]
Instead of taking a true/false flag about secure (https vs http) why not use protocol agnostic?

`//some.url/whatever`

**Comment by emerleite** [comment]
Nice. I'll change it. Thanks.

**Comment by emerleite** [comment]
I think it's not possible, because it's not only the protocol, but the base url.
http://www.gravatar.com/avatar/"
https://secure.gravatar.com/avatar/

**Comment by ProLoser** [comment]
https://www.gravatar.com/avatar/ works fine for me

**Comment by igorprado** [comment]
Any news on this?

**Comment by emerleite** [comment]
You can make a pull request and I'll try it and then accept, if ok. Or you can wait and I'll take a look.

Cheers,

**Comment by igorprado** [comment]
Done, @emerleite  :)

**Comment by emerleite** [comment]
Closed By: https://github.com/emerleite/node-gravatar/pull/17
