### ISSUE TITLE
Extend command line interface to include profile

### ISSUE THREAD

**Issue by lindell** [emerleite/node-gravatar#27]
I was thinking about including the profile url as a part of the CLI. 
If I'm doing it I will use [commander.js](https://github.com/tj/commander.js/blob/master/index.js) as an dependency. Does this sound like something you would merge since the project does not have any (non dev) dependencies at the moment.

**Comment by emerleite** [comment]
Hi @lindell,

I'm not sure if add a dependency is something good for this moment, but a PR with profile url as part of the CLI could be really nice ;)

What do you think?
