### ISSUE TITLE
Need to redirect to an another pic if the gravathar  does not exists

### ISSUE THREAD

**Issue by shameemz** [emerleite/node-gravatar#31]

**Comment by emerleite** [comment]
Hi @shameemz, could you give me an example?

**Comment by lindell** [comment]
I would guess he means that the when you use an email like: does@not.exist it should give an url to an image. [But it does.](https://s.gravatar.com/avatar/c9bbc3f4247c9cb1cca825c5824781b8?size=500&default=retro) So I don't understand why the issue is opened.

**Comment by emerleite** [comment]
@shameemz can you confirm that is @lindell is saying?

**Comment by shameemz** [comment]
what @lindell saying is correct?

**Comment by lindell** [comment]
@shameemz Could you describe the problem with a little bit more detail?

**Comment by rukshn** [comment]
I think it's how Slack is doing, if the user has a gravatar for that email it will show that gravatar, but if they don't have a gravatar they show a slack icon type gravatar. 

So I hope the op is asking in how to do something like that :)

**Comment by brugnara** [comment]
try with the `default` param. Passing `404` it will return nothing (404) if no gravatar is found.

The link you pasted, has `default=retro`. Try with `default=404`:

```
https://s.gravatar.com/avatar/c9bbc3f4247c9cb1cca825c5824781b8?size=500&default=404
```

Hope this helps.

**Comment by shameemz** [comment]
gravatar.url('example@example.com', {s: 10, r: 'pg', d: 'http://example.com/defaultavatar.jpg'});
Above code resolved my problem.

I was looking for an option to give defaultavatar image.

**Comment by magical-mishka** [comment]
Adding an absolute URL as a default option creates a relative link to a URL rooted at http://i0.wp.com/
