### ISSUE TITLE
Needs option for client-side crypto

### ISSUE THREAD

**Issue by goatandsheep** [emerleite/node-gravatar#34]
For frameworks, such as [react-native](https://github.com/facebook/react-native) that cannot load native node modules, you need to use [blueimp-md5](https://www.npmjs.com/package/blueimp-md5) instead of `crypto`.

**Comment by emerleite** [comment]
Hi @goatandsheep. I guess it's a good option to use [blueimp-md5](https://www.npmjs.com/package/blueimp-md5) instead of `crypto` to solve this.
