### ISSUE TITLE
cant load gravator from node modules, error cant find a declaration file for module 'gravator

### ISSUE THREAD

**Issue by kennethsimon** [emerleite/node-gravatar#43]

**Comment by s1moe2** [comment]
Should be `require('node-gravatar')`. The functions are also wrongly documented. This was probably abandoned a long time ago.

**Comment by emerleite** [comment]
@kennethsimon should be require('gravatar'), not **gratator**. 

@s1moe2 the project is not abandoned - https://www.npmjs.com/package/gravatar/v/1.7.0. Please feel free to contribute anytime you want.

**Comment by emerleite** [comment]
Thanks @s1moe2. I'll take a look on this.

**Comment by emerleite** [comment]
@s1moe2 can you post a pastebin or something with your code? I did a sample with Node 11 and everything went well:

```sh
npm install gravatar
```

```js
var gravatar = require('gravatar');
console.log(gravatar.url('emerleite@gmail.com'));
```

Can you reproduce something like this?

**Comment by emerleite** [comment]
Cloud be. I'll close this.

**Comment by avinash-kale** [comment]
a
